name = "lumos-prime" # Replace with your worker's name
main = "./.output/server/index.mjs"
workers_dev = true # Set to false if deploying to a custom domain
compatibility_date = "2024-01-18" # Today's date, update as necessary
