
name: Deploy to Cloudflare Workers with Bun

# Trigger the workflow on push to main branch or manually
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Bun
      run: |
        curl -fsSL https://bun.sh/install | bash
        echo "$HOME/.bun/bin" >> $GITHUB_PATH

    - name: Install dependencies using Bun
      run: bun install

    - name: Build the project using Bun
      run: bun run build

    - name: Install Wrangler CLI
      run: bun add -D wrangler

    - name: Publish to Cloudflare Workers
      run: wrangler publish
      env:
        CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
