name: Deploy to Cloudflare Workers with Bun

# Trigger the workflow on push to main branch or manually
on:
  push:
    branches: ['main', 'develop']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@main

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: "20"
        cache: ${{ steps.detect-package-manager.outputs.manager }}

    - name: Setup Bun
      uses: oven-sh/setup-bun@v1.1.1

    - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ubuntu-latest-node-v20-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/bun.lockb')) }}

    - name: Install Dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: bun install

    - name: Build
      run: bun run build
      env:
          NITRO_PRESET: cloudflare
          NUXT_SSR: 'true'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@main
    - name: Deploy to Cloudflare Workers
      uses: cloudflare/wrangler-action@v3
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        command: publish --name lumos-prime-${{ github.ref_name }}
