name: Deploy to Cloudflare Workers with Bun

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@main

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: "20"

    - name: Setup Bun
      uses: oven-sh/setup-bun@v1.1.1

    - name: Restore cached deps
      id: cache-restore
      uses: actions/cache/restore@v4
      with:
        path: |
          node_modules
          .nuxt
        key: ${{ runner.os }}-${{ hashFiles('**/bun.lockb') }}

    - name: Cache save deps
      id: cache-primes-save
      uses: actions/cache/save@v4
      with:
        path: |
          node_modules
          .nuxt
        key: ${{ steps.cache-primes-restore.outputs.cache-primary-key }}

    - name: Install Dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: bun install

    - name: Build
      run: bun run build
      env:
          NITRO_PRESET: cloudflare
          NUXT_SSR: 'true'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1.1.1

    - uses: actions/checkout@main
    - name: Deploy to Cloudflare Workers
      uses: cloudflare/wrangler-action@v3
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        packageManager: bun
        command: deploy --name lumos-prime-${{ github.ref_name }}
